config/routes.rb
Feedback::Application.routes.draw do
  
  resources :problem_fields
  
  resources :problem_types do
    collection do
      get :export_to_xml
      post :import_from_xml
    end
    
    member do
    
    end
  end
  resources :problem_types

  resources :problem_reports do
    collection do
      post :reply
      post :upload_attachement
    end
    
    member do
    
    end
  end
  resources :problem_reports
  
  match '/simple_captcha(/:action)' => 'simple_captcha', :as => :simple_captcha
 
  # -- 用户登录认证相关 --
  root :to => 'index#index'
  get  '/login'  => 'sessions#new'
  post '/login'  => 'sessions#create'
  get  '/logout' => 'sessions#destroy'
  
  get  '/signup'        => 'signup#form'
  post '/signup_submit' => 'signup#form_submit'
end

 

app/views/index/index.html.haml
.page-welcome.bold 欢迎你，#{current_user.name}

.page-auth-intro
  .title 关于如何在开发中使用用户验证的说明
  .p
    在 View 和 Controller 层，可以使用以下方法
  .p
    .bold current_user
    获得当前登录的用户对象。如果没有登录，则返回 nil
  .p
    .bold logged_in?
    判断当前是否是登录状态

 
.page-to-votes
  =link_to '问题列表','/problem_reports'

  - if current_user.is_admin?
    = link_to '问题类别列表', problem_types_path
    = link_to '问题的内容字段', new_problem_field_path

.page-to-logout
  =link_to "退出登录","/logout"

app/views/index/login.html.haml
-htitle '用户登录'

.page-login
  =flash_info
  =form_tag('/login',{:class=>'login-form'}) do
    .field
      %label 电子邮箱 / 用户名
      =text_field_tag :email, params[:email]
    .field
      %label 密码
      =password_field_tag :password, params[:password]
    .field
      %span=check_box_tag :remember_me, params[:remember_me], true
      %span 下次记住我
    .field
      %a.form-submit-button{:href=>'javascript:;'} 登录
      %a.to-signup{:href=>'/signup'} 注册一个新账号