config/routes.rb
Feedback::Application.routes.draw do
  
  resources :problem_fields
  
  resources :problem_types do
    collection do
      get :export_to_xml
      post :import_from_xml
    end
    
    member do
    
    end
  end
  resources :problem_types

  resources :problem_reports do
    collection do
      post :reply
      post :upload_attachement
    end
    
    member do
    
    end
  end
  resources :problem_reports
  
  match '/simple_captcha(/:action)' => 'simple_captcha', :as => :simple_captcha
 
  # -- 用户登录认证相关 --
  root :to => 'index#index'
  get  '/login'  => 'sessions#new'
  post '/login'  => 'sessions#create'
  get  '/logout' => 'sessions#destroy'
  
  get  '/signup'        => 'signup#form'
  post '/signup_submit' => 'signup#form_submit'
end

 

app/controllers/problem_types_controller.rb
class ProblemTypesController < ApplicationController
  # GET /problem_types
  # GET /problem_types.json
  def index
    @problem_types = ProblemType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @problem_types }
    end
  end

  # GET /problem_types/1
  # GET /problem_types/1.json
  def show
    @problem_type = ProblemType.find(params[:id])
    @problem_fields = @problem_type.problem_fields

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @problem_fields }
      format.json { render :json => @problem_type }
    end
  end

  # GET /problem_types/new
  # GET /problem_types/new.json
  def new
    @problem_type = ProblemType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @problem_type }
    end
  end

  # GET /problem_types/1/edit
  def edit
    @problem_type = ProblemType.find(params[:id])
  end

  # POST /problem_types
  # POST /problem_types.json
  def create
    @problem_type = current_user.problem_types.build(params[:problem_type])

    respond_to do |format|
      if @problem_type.save
        format.html { redirect_to @problem_type, :notice => 'Problem type was successfully created.' }
        format.json { render :json => @problem_type, :status => :created, :location => @problem_type }
      else
        format.html { render :action => "new" }
        format.json { render :json => @problem_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /problem_types/1
  # PUT /problem_types/1.json
  def update
    @problem_type = ProblemType.find(params[:id])

    respond_to do |format|
      if @problem_type.update_attributes(params[:problem_type])
        format.html { redirect_to @problem_type, :notice => 'Problem type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @problem_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /problem_types/1
  # DELETE /problem_types/1.json
  def destroy
    @problem_type = ProblemType.find(params[:id])
    @problem_type.destroy

    respond_to do |format|
      format.html { redirect_to problem_types_url }
      format.json { head :ok }
    end
  end
  
  def export_to_xml
    @problem_type = ProblemType.find(params[:id])
    @entries = @problem_type.problem_fields

    builder = Nokogiri::XML::Builder.new do |xml|
      xml.root {
        xml.objects {
          @entries.each do |o|
            xml.object(
              :problem_type_id => o.problem_type_id, 
              :name => o.name, 
              :field_type => o.field_type
            )
          end
        }
      }
    end
    
    send_data builder.to_xml,
      :type => 'text/xml; charset=UTF-8;',
      :disposition => "attachment; filename=entries.xml"
  end
  
  def import_from_xml
    file_type = MIME::Types.type_for(params[:xmlfile].original_filename).first.content_type
    unless file_type == 'application/xml'
      flash[:notice] = '文件格式错误'
    else
      
      # 读取上传的 xml 文件内容
      xmlfile = params[:xmlfile]
      if xmlfile.respond_to?(:read)
        xml_contents = xmlfile.read
      else xmlfile.respond_to?(:path)
        xml_contents = File.read(xmlfile.path)
      end
      
      # 解析 xml 文件，插入数据库
      xml = Nokogiri::XML(xml_contents)
      xml.xpath('//root/objects/object').each do |node|
        if node['name'].blank? || node['problem_type_id'].blank? || node['field_type'].blank?
          flash[:notice] = '文件格式错误'
        else
          ProblemField.create(
            :name => node['name'],
            :problem_type_id => node['problem_type_id'],
            :field_type => node['field_type']
          )
        end
        
      end
      
    end

    redirect_to :back
    
  end
  
end

app/helpers/problem_types_helper.rb
module ProblemTypesHelper
end

app/views/problem_types/_form.html.erb
<%= form_for(@problem_type) do |f| %>
  <% if @problem_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem_type.errors.count, "error") %> prohibited this problem_type from being saved:</h2>

      <ul>
      <% @problem_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :creator_id %><br />
    <%= f.text_field :creator_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problem_types/edit.html.erb
<h1>Editing problem_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem_type %> |
<%= link_to 'Back', problem_types_path %>

app/views/problem_types/index.html.erb
<h1>Listing problem_types</h1>

<table>
  <tr>
    <th>Creator</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @problem_types.each do |problem_type| %>
  <tr>
    <td><%= problem_type.creator_id %></td>
    <td><%= problem_type.name %></td>
    <td><%= link_to '导出配置', "/problem_types/export_to_xml?id=#{problem_type.id}", :target => '_blank' %></td>
    <td><%= link_to 'Show', problem_type %></td>
    <td><%= link_to 'Edit', edit_problem_type_path(problem_type) %></td>
    <td><%= link_to 'Destroy', problem_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Problem type', new_problem_type_path %>

app/views/problem_types/new.html.haml
= form_for @problem_type do |f|
  %p
    名称
    = f.text_field :name
      
  .field
    %a.form-submit-button{:href=>'javascript:;'} 发送

%p
  = link_to 'Back', problem_types_path

app/views/problem_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Creator:</b>
  <%= @problem_type.creator_id %>
</p>

<p>
  <b>Name:</b>
  <%= @problem_type.name %>
</p>


<%= link_to 'Edit', edit_problem_type_path(@problem_type) %> |
<%= link_to 'Back', problem_types_path %>